Regenerate Livepeer Go SDK
livepeer/livepeer-go pull request #5
Opened 2024-03-14 11:09 UTC by leszko

@suhailkakar please check and merge.

Please update README.md.

I tested and it works fine. I generated if from [api-schems.yaml](https://github.com/livepeer/studio/blob/master/packages/api/src/schema/api-schema.yaml)

Steps to reproduce:
1. Start from commandline `speakeasy quickstart`
2. Choose [api-schems.yaml](https://github.com/livepeer/studio/blob/master/packages/api/src/schema/api-schema.yaml)
3. Type `liveepeer` as the name
4. Type `github.com/livepeer/livepeer-go` as the package name

2024-03-15 16:22 UTC, 0xcadams requested changes
Not sure who is owning this to the finish line, but we should update README and make sure that package name is `livepeer` instead of `livepeergo` before merging/publishing.

2024-03-15 16:22 UTC, 0xcadams commented on .speakeasy/workflow.yaml
> +            - location: /Users/rafalleszko/repos/studio/packages/api/src/schema/api-schema.yaml
Could we update this to point to the Livepeer Studio API schema?

2024-03-15 16:22 UTC, 0xcadams commented on README.md
> +	livepeergo "github.com/livepeer/livepeer-go"
Could we update this to be `livepeer` instead of `livepeergo`

2024-03-15 16:22 UTC, 0xcadams commented on livepeer.go
> +package livepeergo
Does this define the package name? Could this be just `livepeer`?

2024-03-15 16:22 UTC, 0xcadams commented on USAGE.md
> +	livepeergo "github.com/livepeer/livepeer-go"
Again, here should be `livepeer`

2024-03-18 08:09 UTC, leszko commented
@0xcadams @suhailkakar As discussed in Discord, feel free to take over this PR and apply all the changes you put in the comment.

2024-03-26 17:03 UTC, 0xcadams approved these changes
🚢

2024-03-26 17:03 UTC, merged